name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Start server
        run: node server.js
      - name: Run build
        uses: npm serve
      - name: Run tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          headed: true