name: End-to-end tests
on: [push]
jobs:
  linux-chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Run tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome

  macos-chrome:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Run tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome

  macos-headed-chrome:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Run tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          headed: true

  macos-firefox:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Run tests
        uses: cypress-io/github-action@v5
        with:
          browser: firefox

  macos-headed-firefox:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Run tests
        uses: cypress-io/github-action@v5
        with:
          browser: firefox
          headed: true

  macos-edge:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Run tests
        uses: cypress-io/github-action@v5
        with:
          browser: edge

  macos-headed-edge:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Run tests
        uses: cypress-io/github-action@v5
        with:
          browser: edge
          headed: true

  windows-chrome:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Run tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome

  windows-headed-chrome:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Run tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          headed: true

  windows-firefox:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Run tests
        uses: cypress-io/github-action@v5
        with:
          browser: firefox
  windows-edge:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Run tests
        uses: cypress-io/github-action@v5
        with:
          browser: edge


